=== davitp/DPC/DPC.Processor/LanguageSchema/LanguageDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="LanguageDefinition"
    targetNamespace="http://github.com/davitp/DPC/LanguageDefinition.xsd"
    elementFormDefault="qualified"
    xmlns="http://github.com/davitp/DPC/LanguageDefinition.xsd"
    xmlns:mstns="http://github.com/davitp/DPC/LanguageDefinition.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:simpleType name="LogicalOperatorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="{AND}"/>
      <xs:enumeration value="{OR}"/>
      <xs:enumeration value="{NOT}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PredicateType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="{Equal}" />
      <xs:enumeration value="{NotEqual}" />
      <xs:enumeration value="{Less}" />
      <xs:enumeration value="{Greater}" />
      <xs:enumeration value="{LessOrEqual}" />
      <xs:enumeration value="{GreaterOrEqual}" />
      <xs:enumeration value="{Between}" />
      <xs:enumeration value="{HasSubstring}" />
      <xs:enumeration value="{IsSubstring}" />
      <xs:enumeration value="{IsZero}" />
      <xs:enumeration value="{In}" />
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="LogicalOperatorDefinitionType">
    <xs:sequence>
      <xs:element name="Definition" type="LogicalOperatorType" />
      <xs:element name="Implementation" type="xs:string" />
      <xs:element name="Dimention" type="xs:int" default="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PredicateDefinitionType">
    <xs:sequence>
      <xs:element name="Definition"  type="PredicateType"/>
      <xs:element name="Implementation"  type="xs:string"/>
      <xs:element name="Dimention" type="xs:int" default="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="LogicalOperatorDefinitionsType">
    <xs:sequence>
      <xs:element name="LogicalOperatorDefinition" type="LogicalOperatorDefinitionType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PredicateDefinitionsType" >
    <xs:sequence>
      <xs:element name="PredicateDefinition" type="PredicateDefinitionType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="LanguageMetadataDefinitionType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="LanguageDefinitionType">
    <xs:sequence>
      <xs:element name="LogicalOperatorDefinitions" type="LogicalOperatorDefinitionsType" />
      <xs:element name="PredicateDefinitions" type="PredicateDefinitionsType" />
      <xs:element name="MetadataDefinition" type="LanguageMetadataDefinitionType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:element name="LanguageDefinitions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LanguageDefinition"  type="LanguageDefinitionType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== davitp/DPC/DPC.UnitTests/Definitions/LanguageDefinitions.xml
<?xml version="1.0"  encoding="utf-8" ?>
<LanguageDefinitions
  xmlns="http://gnu.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://gnu.org ..\..\DPC.Specification\LanguageSchema\LanguageDefinition.xsd" >

  <LanguageDefinition>
    
    <MetadataDefinition Name="SQL" OpenBracket="(" CloseBracket=")" Prioritizer="BracketPrioritizer" />

    <LogicalOperatorDefinitions>
      <LogicalOperatorDefinition Operator="{AND}"  Implementation="{0} AND {1}"/>
      <LogicalOperatorDefinition Operator="{OR}" Implementation="{0} OR {1}" />
      <LogicalOperatorDefinition Operator="{NOT}" Implementation="NOT {0}" />
    </LogicalOperatorDefinitions>
    
    <PredicateDefinitions>
      <PredicateDefinition Operator="{Equal}" Implementation="{0} = {1}"/>
      <PredicateDefinition Operator="{NotEqual}" Implementation="{0} != {1}"/>
      <PredicateDefinition Operator="{Less}" Implementation="{0} &#60; {1}"/>
      <PredicateDefinition Operator="{Greater}" Implementation="{0} > {1}"/>
      <PredicateDefinition Operator="{LessOrEqual}" Implementation="{0} &#60;= {1}" />
      <PredicateDefinition Operator="{GreaterOrEqual}" Implementation="{0} >= {1}" />
      <PredicateDefinition Operator="{Between}" Implementation=" {0} BETWEEN {1} AND {2}"/>
      <PredicateDefinition Operator="{HasSubstring}" Implementation="{0} like %{1}%"/>
      <PredicateDefinition Operator="{IsSubstring}" Implementation="{1} like %{0}%"/>
      <PredicateDefinition Operator="{IsZero}" Implementation="{0} = 0"/>
      <PredicateDefinition Operator="{In}" Implementation="{0} in {1}"/>
      <PredicateDefinition Operator="{Truth}" Implementation="TRUE"/>
      <PredicateDefinition Operator="{Falsehood}" Implementation="FALSE"/>
    </PredicateDefinitions>
  </LanguageDefinition>
</LanguageDefinitions>

=== davitp/DPC/Sigma.UnitTests/Definitions/LanguageDefinitions.xml
<?xml version="1.0"  encoding="utf-8" ?>
<LanguageDefinitions
  xmlns="http://gnu.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://gnu.org ..\..\..\Sigma.Specification\LanguageSchema\LanguageDefinition.xsd" >

  <LanguageDefinition Name="SQL">
    
    <MetadataDefinition OpenBracket="(" CloseBracket=")" Prioritizer="BracketPrioritizer" />

    <LogicalOperatorDefinitions>
      <LogicalOperatorDefinition Operator="{AND}"  Implementation="{0} AND {1}"/>
      <LogicalOperatorDefinition Operator="{OR}" Implementation="{0} OR {1}" />
      <LogicalOperatorDefinition Operator="{NOT}" Implementation="NOT {0}" />
    </LogicalOperatorDefinitions>
    
    <PredicateDefinitions>
      <PredicateDefinition Operator="{Equal}" Implementation="{0} = {1}"/>
      <PredicateDefinition Operator="{NotEqual}" Implementation="{0} != {1}"/>
      <PredicateDefinition Operator="{Less}" Implementation="{0} &#60; {1}"/>
      <PredicateDefinition Operator="{Greater}" Implementation="{0} > {1}"/>
      <PredicateDefinition Operator="{LessOrEqual}" Implementation="{0} &#60;= {1}" />
      <PredicateDefinition Operator="{GreaterOrEqual}" Implementation="{0} >= {1}" />
      <PredicateDefinition Operator="{Between}" Implementation=" {0} BETWEEN {1} AND {2}"/>
      <PredicateDefinition Operator="{HasSubstring}" Implementation="{0} like %{1}%"/>
      <PredicateDefinition Operator="{IsSubstring}" Implementation="{1} like %{0}%"/>
      <PredicateDefinition Operator="{IsZero}" Implementation="{0} = 0"/>
      <PredicateDefinition Operator="{In}" Implementation="{0} in {1}"/>
      <PredicateDefinition Operator="{Truth}" Implementation="TRUE"/>
      <PredicateDefinition Operator="{Falsehood}" Implementation="FALSE"/>
    </PredicateDefinitions>
  </LanguageDefinition>

  <LanguageDefinition Name="Armenian">

    <MetadataDefinition OpenBracket="(" CloseBracket=")" Prioritizer="BracketPrioritizer" />

    <LogicalOperatorDefinitions>
      <LogicalOperatorDefinition Operator="{AND}"  Implementation="{0} և {1}"/>
      <LogicalOperatorDefinition Operator="{OR}" Implementation="{0} կամ {1}" />
    </LogicalOperatorDefinitions>

    <PredicateDefinitions>
      <PredicateDefinition Operator="{Equal}" Implementation="{0}-ը հավասար է {1}-ի"/>
      <PredicateDefinition Operator="{Less}" Implementation="{0}-ը փոքր է {1}-ից"/>
      <PredicateDefinition Operator="{IsZero}" Implementation="{0}-ը զրո է"/>
    </PredicateDefinitions>
  </LanguageDefinition>
</LanguageDefinitions>
